services:
  - type: web
    name: my-backend
    repo: https://github.com/ghinashoury/Neuralift.git
    branch: main
    env: node
    buildCommand: ""
    startCommand: "npm start"
    envVars:
      - key: MONGO_URI
        sync: false
